services:
  # Message Broker
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - microservices-network

  # Microserviços
  ms-auth:
    build: ./back-end/ms-auth
    container_name: ms-auth
    ports:
      - "8081:8080"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
    networks:
      - microservices-network

  ms-user:
    build: ./back-end/ms-user
    container_name: ms-user
    ports:
      - "8082:8080"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
    networks:
      - microservices-network

  ms-roadmap:
    build: ./back-end/ms-roadmap
    container_name: ms-roadmap
    ports:
      - "8083:8080"
    networks:
      - microservices-network

  ms-course:
    build: ./back-end/ms-course
    container_name: ms-course
    ports:
      - "8084:8080"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  rabbitmq_data:
